---
- name: Add repos /etc/yum.repos.d/sensu.repo
  template:
       src: "../../templates/etc/yum.repos.d/repo.template.j2"
       dest: "/etc/yum.repos.d/sensu.repo"
       owner: root
       group: root
       mode: 0644
  with_items:
       - name: "sensu"
         baseurl: "http://repos.sensuapp.org/yum/el/$basearch/"
         gpgcheck: 0
         enabled: 1

- name: install sensu
  yum: name=sensu state=installed

# Checks prerequisites
- name: install common packages sensu
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
       - ruby
       - sudo
       - bc
       - gem
       - gcc-c++
       - ruby-devel
       - make
       - python-requests
       #- http://rpmfind.net/linux/centos/7.1.1503/updates/x86_64/Packages/ruby-devel-2.0.0.598-25.el7_1.x86_64.rpm

# Checks
- name: install common gems sensu
  environment: proxy_env
  gem:
    name: "{{ item }}"
    state: present
    user_install: no
  with_items:
       - sensu-plugin
       - sensu-plugins-process-checks
       - sensu-plugins-network-checks
       - sensu-plugins-load-checks
       - sensu-plugins-memory-checks
       - sensu-plugins-disk-checks
       - sensu-plugins-http

- name: ensure service sensu-client started
  service:
    name: sensu-client
    state: started
    enabled: yes
  when: dockerbuild is undefined
