---
- name: Add proxy in /etc/yum.conf
  lineinfile:
    dest: /etc/yum.conf
    regexp: "^proxy=.*"
    line: "proxy={{ proxy_env[\'http_proxy\'] }}"
  when: proxy_env['http_proxy']
  tags: proxyenv
