---
- name: add script to setup serviceaccount
  copy:
    src: "tmp/{{ item }}.sh"
    dest: "/tmp/{{ item }}.sh"
    owner: root
    mode: 0700
  with_items:
    - metrics_sa
    - monitoring_sa
    - fetch_token


- name: create fact directory
  file:
    path: /etc/ansible/facts.d
    state: directory

- name: create service account metrics
  command: /tmp/metrics_sa.sh
  register: command_result
  changed_when: "command_result.stdout.find('CHANGED') != -1"
  when: "'monitoring' in groups and inventory_hostname == masters[0]"

- name: create service account monitoring
  command: /tmp/monitoring_sa.sh
  register: command_result
  changed_when: "command_result.stdout.find('CHANGED') != -1"
  when: inventory_hostname == masters[0]

- name: fetch tokens for serviceaccounts metrics
  command: "/tmp/fetch_token.sh metrics"
  always_run: yes
  changed_when: False
  register: token_metrics

- name: fetch tokens for serviceaccounts monitoring
  command: "/tmp/fetch_token.sh monitoring"
  always_run: yes
  changed_when: False
  register: token_monitoring

- name: add token metrics to fact openshift_data
  ini_file:
    dest: /etc/ansible/facts.d/openshift_data.fact
    section: tokens
    option: metrics
    value: "{{ token_metrics.stdout }}"
  when: token_metrics|success

- name: add token monitoring to fact openshift_data
  ini_file:
    dest: /etc/ansible/facts.d/openshift_data.fact
    section: tokens
    option: monitoring
    value: "{{ token_monitoring.stdout }}"
  when: token_monitoring|success

- name: re-read facts after adding custom fact
  setup: filter=ansible_local
