---
nodes_manage_docker_storage: "{{ manage_docker_storage | default('true') }}"


nodes_deployment_type: "{{ deployment_type | default('openshift') }}"
nodes_deamon_name: "{% if deployment_type == 'origin' %}origin-node{% elif deployment_type == 'openshift-enterprise' %}atomic-openshift-node{% else %}openshift-node{% endif %}"
nodes_etc_config: "{% if deployment_type == 'origin' or deployment_type == 'openshift-enterprise' %}origin{% else %}openshift{% endif %}"

docker_vg: "{{ customer_docker_vg | default('docker-vg') }}"
